# https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    # below does not seem to work with the open-webui image, but leaving it here for reference
    #user: "1000:1000" # Set the user of the container to match the host's user ID and group ID
    container_name: open-webui
    volumes:
      - /home/jack/open-webui:/app/backend/data
    network_mode: "host"
    environment:
      - 'PORT=3000'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]